---
- name: ansible play
  hosts: dev
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: install Python
      apt:
        name: python3
        state: present

    - name: install Apache2
      apt:
        name: apache2
        state: present

    - name: run apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: create content
      copy:
        src: /home/ubuntu/dist/*
        dest: /var/www/html/

    - name: restart apache
      service:
        name: apache2
        state: restarted
