---
- name: play ansible
  hosts: dev
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: install Python
      package:
        name: python
        state: present

    - name: install httpd
      yum:
        name: httpd
        state: latest
        use_backend: yum

    - name: run httpd
      service:
        name: httpd
        state: started

    - name: create content
      copy:
        content: "Congratulations on installing ansible"
        dest: /var/www/html/index.html
