# ---
# ## Boolean conditional check for installing apache
# - name: Install Apache web server
#   apt:
#     name: apache2
#     state: absent
#   when: install_apache_flag

# ## putting multiple condition using ansible_facts
# - name: Combine conditions using ansible facts
#   debug:
#     var: ansible_facts['kernel_version']
#   when:
#     - ansible_facts['os_family'] == "Debian"
#     - ansible_facts['distribution_major_version'] == "20"

# ## Setting complex condition
# - name: Setting complex condition
#   debug:
#     var: ansible_facts['kernel_version']
#   when:
#     - ansible_facts['os_family'] == "Debian"
#     - ansible_facts['distribution_major_version'] == "20"
