---
- name: Install Apache web server
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Start Apache Service
  become: yes
  service:
    name: apache2
    state: started
  register: status
- debug:
    var: status.state
